### ISSUE TITLE
Padronização de extensões dos áudios

### ISSUE THREAD

**Issue by 7robertodantas** [MeFormei/sounds#2]
Verificar e realizar padronização dos áudios em um mesmo formato (que seja leve e que não precise de extensões para rodar). Visto que alguns estão em mid, outros em mp3 e outros em wav.

Pode-se manter backup no drive das outras extensões que permitem modificações, e no repositório suas versões finais com extensões padronizadas.

**Comment by xandecarvalhojr** [comment]
Foram padronizados. Os efeitos de som são agora .mp3 e as soundtracks são .mid
